/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package savingstudentsinadatabase;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author styde
 */
public class AddJFrame extends javax.swing.JInternalFrame {
     student s=null;
        ArrayList<Grade> grade = new ArrayList<>();
SQL sql;
    /**
     * Creates new form AddJFrame
     */
    public AddJFrame() {
        initComponents();
         try {
             sql=new SQL();
         } catch (ClassNotFoundException ex) {
System.out.println(ex);
         } catch (SQLException ex) {
System.out.println(ex);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fairstnameJTextfield = new javax.swing.JTextField();
        lastnamejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        IDjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        GradesnamejTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        gradesjTextField = new javax.swing.JTextField();
        submit_jButton = new javax.swing.JButton();
        male_jRadioButton1 = new javax.swing.JRadioButton();
        female_jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 350));

        jLabel1.setText("Student  first Name  ");

        jLabel2.setText("Student  last Name  ");

        fairstnameJTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fairstnameJTextfieldActionPerformed(evt);
            }
        });
        fairstnameJTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fairstnameJTextfieldKeyTyped(evt);
            }
        });

        lastnamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnamejTextFieldActionPerformed(evt);
            }
        });
        lastnamejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastnamejTextFieldKeyTyped(evt);
            }
        });

        jLabel3.setText("ID");

        IDjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDjTextFieldKeyTyped(evt);
            }
        });

        jLabel4.setText("sex ");

        jLabel5.setText("grades name");

        GradesnamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradesnamejTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("grades ");

        gradesjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gradesjTextFieldKeyTyped(evt);
            }
        });

        submit_jButton.setText("Submit");
        submit_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        buttonGroup1.add(male_jRadioButton1);
        male_jRadioButton1.setText("male");
        male_jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleradiobuttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(female_jRadioButton2);
        female_jRadioButton2.setText("female");
        female_jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadiobuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fairstnameJTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(lastnamejTextField)
                            .addComponent(IDjTextField)
                            .addComponent(GradesnamejTextField)
                            .addComponent(gradesjTextField)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(male_jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(female_jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(submit_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(fairstnameJTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(male_jRadioButton1)
                    .addComponent(female_jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GradesnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submit_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fairstnameJTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fairstnameJTextfieldActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_fairstnameJTextfieldActionPerformed

    private void lastnamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnamejTextFieldActionPerformed

    private void GradesnamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradesnamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradesnamejTextFieldActionPerformed

    private void fairstnameJTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fairstnameJTextfieldKeyTyped
        // TODO add your handling code here:
         if ( !((evt.getKeyChar()>='A' && evt.getKeyChar()<='Z')||(evt.getKeyChar()>='a' && evt.getKeyChar()<='z')))
                    evt.consume();
    }//GEN-LAST:event_fairstnameJTextfieldKeyTyped

    private void lastnamejTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastnamejTextFieldKeyTyped
        // TODO add your handling code here:
         if ( !((evt.getKeyChar()>='A' && evt.getKeyChar()<='Z')||(evt.getKeyChar()>='a' && evt.getKeyChar()<='z')))
                    evt.consume();
        
    }//GEN-LAST:event_lastnamejTextFieldKeyTyped

    private void IDjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDjTextFieldKeyTyped
        // TODO add your handling code here:
         if ( !(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'))
                    evt.consume();
    }//GEN-LAST:event_IDjTextFieldKeyTyped

    private void maleradiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleradiobuttonActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_maleradiobuttonActionPerformed

    private void gradesjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gradesjTextFieldKeyTyped
      
 
       // TODO add your handling code here:
       if ( !(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'))
                    evt.consume();
       
       
    }//GEN-LAST:event_gradesjTextFieldKeyTyped

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:

        Grade g;
        if (grade == null) {
    grade = new ArrayList<>();
}
          g=new Grade(GradesnamejTextField.getText(),Integer.parseInt(gradesjTextField.getText()));

       if(male_jRadioButton1.isSelected()&&!(grade.contains(g)))
       {
           
            grade.add(g);
   int sum=0,average=0;
       for(int i=0;i<grade.size();i++){
         sum+= grade.get(i).getGradeValue();
       }
       try{
       average=sum/grade.size();}
catch(ArithmeticException e){
    average=0;
}
      s=new student(Integer.parseInt(IDjTextField.getText()),fairstnameJTextfield.getText(),lastnamejTextField.getText(),male_jRadioButton1.getText(),grade,average);
            try {
                sql.create_or_update(s);
            } catch (ClassNotFoundException | SQLException ex) {
System.out.println(ex);
            }
       }


        if(female_jRadioButton2.isSelected()&& !(grade.contains(g)))
       {
           grade.add(g);
   int sum=0,average=0;
       for(int i=0;i<grade.size();i++){
         sum+= grade.get(i).getGradeValue();
       }
       try{
       average=sum/grade.size();}
catch(ArithmeticException e){
    average=0;
}
       s=new student(Integer.parseInt(IDjTextField.getText()),fairstnameJTextfield.getText(),lastnamejTextField.getText(),female_jRadioButton2.getText(),grade,average);
        try {
                sql.create_or_update(s);
            } catch (ClassNotFoundException | SQLException ex) {
System.out.println(ex);
            }        
       }
       
    }//GEN-LAST:event_SubmitActionPerformed

    private void femaleRadiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadiobuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadiobuttonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GradesnamejTextField;
    private javax.swing.JTextField IDjTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fairstnameJTextfield;
    private javax.swing.JRadioButton female_jRadioButton2;
    private javax.swing.JTextField gradesjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lastnamejTextField;
    private javax.swing.JRadioButton male_jRadioButton1;
    private javax.swing.JButton submit_jButton;
    // End of variables declaration//GEN-END:variables
}
