/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package savingstudentsinadatabase;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author styde
 */
public class changeJFrame extends javax.swing.JInternalFrame {
private SQL sql;
private mainFrame main; 
ArrayList<student> stu = new ArrayList<>();

private int currentIndex=0;
private String last_search="";

    /**
     * Creates new form SearchJFrame
     */
public void show_student(student s){
     firstnamejLabel_edit.setText(s.get_first_name());
        lastnamejLabel_edit.setText(s.get_last_name());
        IDjLabel_edit.setText(String.valueOf(s.getID()));
        sexjLabel_edit.setText(s.get_sex());
        
        gradesnamejTextField.setText(Arrays.toString(s.get_grades_name()));
        gradesjTextField.setText(Arrays.toString(s.get_grades()));
        averagejLabel_edit.setText(String.valueOf(s.get_average()));
}
    /**
     * Creates new form changeJFrame
     */
  public changeJFrame(mainFrame main) {
         this.main=main;

        initComponents();
        try {
        sql=new SQL();
    } catch (ClassNotFoundException ex) {
System.out.println(ex);
    } catch (SQLException ex) {
System.out.println(ex);
}}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        searchjButton = new javax.swing.JButton();
        searchtermjTextField = new javax.swing.JTextField();
        search_termjLabel1 = new javax.swing.JLabel();
        IDjLable = new javax.swing.JLabel();
        IDjLabel_edit = new javax.swing.JLabel();
        firstnamejLabel_edit = new javax.swing.JLabel();
        firstnamejLable = new javax.swing.JLabel();
        lastnamejLabel_edit = new javax.swing.JLabel();
        lastnamejLable = new javax.swing.JLabel();
        sexjLable = new javax.swing.JLabel();
        sexjLabel_edit = new javax.swing.JLabel();
        gradenamejLable = new javax.swing.JLabel();
        gradejLable = new javax.swing.JLabel();
        averagejLabel_edit = new javax.swing.JLabel();
        averagejLabel = new javax.swing.JLabel();
        gradesnamejTextField = new javax.swing.JTextField();
        gradesjTextField = new javax.swing.JTextField();
        changegradejButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchjButton.setText("search");
        searchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButtonActionPerformed(evt);
            }
        });

        searchtermjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtermjTextFieldActionPerformed(evt);
            }
        });

        search_termjLabel1.setText("search term");

        IDjLable.setText("ID");

        firstnamejLable.setText("first name");

        lastnamejLable.setText("last name");

        sexjLable.setText("sex");

        gradenamejLable.setText("grade name");

        gradejLable.setText("grade");

        averagejLabel.setText("average");

        gradesnamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradesnamejTextFieldActionPerformed(evt);
            }
        });

        changegradejButton1.setText("changegrade");
        changegradejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changegradejButton1ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(searchjButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(searchtermjTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(search_termjLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(IDjLable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(IDjLabel_edit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(firstnamejLabel_edit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(firstnamejLable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lastnamejLabel_edit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lastnamejLable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(sexjLable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(sexjLabel_edit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(gradenamejLable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(gradejLable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(averagejLabel_edit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(averagejLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(gradesnamejTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(gradesjTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(changegradejButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(averagejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDjLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_termjLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstnamejLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastnamejLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sexjLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gradenamejLable, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(gradejLable, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gradesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(averagejLabel_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(changegradejButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(IDjLabel_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                        .addComponent(firstnamejLabel_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lastnamejLabel_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(sexjLabel_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchtermjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(gradesnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(searchtermjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(search_termjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IDjLabel_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDjLable, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firstnamejLable, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnamejLabel_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastnamejLable, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(lastnamejLabel_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sexjLable, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(sexjLabel_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradenamejLable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradesnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gradejLable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gradesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(averagejLabel)
                            .addComponent(averagejLabel_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changegradejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButtonActionPerformed
        // TODO add your handling code here:
       stu = sql.Search_student(searchtermjTextField.getText());
    String term = searchtermjTextField.getText();

    if(!(stu.isEmpty()))
    {
        show_student(stu.get(currentIndex));
        currentIndex++;
           last_search = term;

       }
    else{
        firstnamejLabel_edit.setText(" ");
        lastnamejLabel_edit.setText(" ");
        IDjLabel_edit.setText(" ");
        sexjLabel_edit.setText(" ");
        
        gradesnamejTextField.setText(" ");
        gradesjTextField.setText(" ");
        averagejLabel_edit.setText(" ");
        
    }
    if (currentIndex >= stu.size()) {
        currentIndex = 0;
        stu.clear();
    }
    
    }//GEN-LAST:event_searchjButtonActionPerformed

    private void searchtermjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtermjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtermjTextFieldActionPerformed

    private void gradesnamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradesnamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradesnamejTextFieldActionPerformed

    private void changegradejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changegradejButton1ActionPerformed
        // TODO add your handling code here:
      
 ArrayList<Grade> grade = new ArrayList<>();


      Grade g;
      student s;

        if (grade == null) {
    grade = new ArrayList<>();
}
if(gradesnamejTextField.getText().trim().isEmpty()||gradesjTextField.getText().trim().isEmpty()){
     JOptionPane.showMessageDialog(this, "all fields of grade are required");
     
        }
else{
if(!(gradesnamejTextField.getText().startsWith("["))&&!(gradesnamejTextField.getText().endsWith("]")))
{  
double value=Double.parseDouble(gradesjTextField.getText());
 if ( value< 1 ||value> 100) {
    JOptionPane.showMessageDialog(this, "Enter a grade between 1 and 100");
    return;
}
else{         
g=new Grade(gradesnamejTextField.getText(),value);
try {
        grade=sql.ARRY_GRADE(Integer.parseInt(IDjLabel_edit.getText()));
    } catch (SQLException ex) {
System.out.println(ex);
    }
 grade.add(g);
 }}
 else if(gradesnamejTextField.getText().startsWith("[")&&gradesnamejTextField.getText().endsWith("]"))
{
  String text_grade = gradesjTextField.getText();

text_grade = text_grade.replace("[", "").replace("]", "");

String[] parts = text_grade.split(",");

ArrayList<Double> values = new ArrayList<>();


  String name_grade_text = gradesnamejTextField.getText();

name_grade_text = name_grade_text.replace("[", "").replace("]", "");

String[] parts2 = name_grade_text.split(",");

ArrayList<String> name_grade = new ArrayList<>();

for (String part : parts) {
    values.add(Double.parseDouble(part.trim()));
}
for (String part : parts2) {
    name_grade.add(part.trim());
}
grade.clear();
for(int y=0;y<values.size();y++){
    ;
 if ( values.get(y)< 1 ||values.get(y)> 100) {
    JOptionPane.showMessageDialog(this, "Enter a grade between 1 and 100");
    return;
}
    g=new Grade(name_grade.get(y),values.get(y));
    grade.add(g);
}
  
}

  double average=0;
  double sum=0;
  double size=grade.size();
for(int x=0;x<grade.size();x++){
         sum+= grade.get(x).getGradeValue();
       }
       try{
       average=sum/size;}
catch(ArithmeticException e){
    average=0;
}          
       
          
      s=new student(Integer.parseInt(IDjLabel_edit.getText()),firstnamejLabel_edit.getText(),lastnamejLabel_edit.getText(),sexjLabel_edit.getText(),grade,average);
            try {
                sql.create_or_update(s);
                 averagejLabel_edit.setText(String.valueOf(average));
            } catch (ClassNotFoundException | SQLException ex) {
System.out.println(ex);
            }

       

    }



                                                            main.list();


    }//GEN-LAST:event_changegradejButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDjLabel_edit;
    private javax.swing.JLabel IDjLable;
    private javax.swing.JLabel averagejLabel;
    private javax.swing.JLabel averagejLabel_edit;
    private javax.swing.JButton changegradejButton1;
    private javax.swing.JLabel firstnamejLabel_edit;
    private javax.swing.JLabel firstnamejLable;
    private javax.swing.JLabel gradejLable;
    private javax.swing.JLabel gradenamejLable;
    private javax.swing.JTextField gradesjTextField;
    private javax.swing.JTextField gradesnamejTextField;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel lastnamejLabel_edit;
    private javax.swing.JLabel lastnamejLable;
    private javax.swing.JLabel search_termjLabel1;
    private javax.swing.JButton searchjButton;
    private javax.swing.JTextField searchtermjTextField;
    private javax.swing.JLabel sexjLabel_edit;
    private javax.swing.JLabel sexjLable;
    // End of variables declaration//GEN-END:variables
}
