/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package savingstudentsinadatabase;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author styde
 */
public class deleteJFrame extends javax.swing.JInternalFrame{
SQL sql;

    /**
     * Creates new form deleteJFrame
     */
    public deleteJFrame() {
        initComponents();
    try {
        sql=new SQL();
    } catch (ClassNotFoundException ex) {
System.out.println(ex);
    } catch (SQLException ex) {
System.out.println(ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        deletejTextField1 = new javax.swing.JTextField();
        deletejButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 350));

        jLabel1.setText("ID");

        deletejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejTextField1ActionPerformed(evt);
            }
        });
        deletejTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                deletejTextField1KeyTyped(evt);
            }
        });

        deletejButton1.setText("Delete");
        deletejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(deletejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(deletejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejTextField1ActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_deletejTextField1ActionPerformed

    private void deletejTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deletejTextField1KeyTyped
        // TODO add your handling code here:
          if ( !(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'))
                    evt.consume();
    }//GEN-LAST:event_deletejTextField1KeyTyped

    private void deletejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButton1ActionPerformed
        // TODO add your handling code here:
          int option=0;
                
                option=JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the student? ", " DELETE STUDENT",JOptionPane.YES_NO_CANCEL_OPTION);
                
                if ( option==JOptionPane.YES_OPTION)
                {
              try {
                  if(sql.search_id(Integer.parseInt(deletejTextField1.getText())))
                  { sql.delete_student(Integer.parseInt(deletejTextField1.getText()));
                                JOptionPane.showMessageDialog(null,"The deleted completed successfully ","DELETE END",1);}

                  else{
              JOptionPane.showMessageDialog(null,"the id input that not found in database","NOT Exist id",0);
                      
                  }
              } catch (SQLException ex) {
System.out.println(ex);
              }
                    
                }
    }//GEN-LAST:event_deletejButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletejButton1;
    private javax.swing.JTextField deletejTextField1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
